-- +goose Up
-- Server-to-server credentials. Only the SHA-256 of the secret is stored, like
-- sessions; revoked keys stay as rows (history, and no re-seeding).
CREATE TABLE api_keys (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text        NOT NULL CHECK (name <> ''),
    scope        text        NOT NULL CHECK (scope IN ('read', 'write')),
    last4        text        NOT NULL,
    token_hash   bytea       NOT NULL UNIQUE,
    created_by   text        NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    revoked_at   timestamptz
);

-- +goose Down
DROP TABLE api_keys;
