-- +goose Up
-- Core schema. Money is stored as bigint cents; timestamps are timestamptz.

CREATE TABLE members (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text        NOT NULL,
    email          text        NOT NULL,
    role           text        NOT NULL CHECK (role IN ('owner', 'admin', 'editor', 'support', 'viewer')),
    status         text        NOT NULL DEFAULT 'invited' CHECK (status IN ('active', 'invited', 'suspended')),
    mfa            boolean     NOT NULL DEFAULT false,
    password_hash  text        NOT NULL DEFAULT '',
    last_active_at timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX members_email_key ON members (lower(email));
-- Exactly one owner per workspace.
CREATE UNIQUE INDEX members_single_owner ON members (role) WHERE role = 'owner';

-- Only a SHA-256 of the token is stored, so a leaked table can't be replayed.
CREATE TABLE sessions (
    token_hash bytea       PRIMARY KEY,
    member_id  bigint      NOT NULL REFERENCES members (id) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_member_idx ON sessions (member_id);
CREATE INDEX sessions_expires_idx ON sessions (expires_at);

CREATE TABLE products (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             text        NOT NULL,
    sku              text        NOT NULL UNIQUE,
    category         text        NOT NULL CHECK (category IN ('Audio', 'Wearables', 'Lighting', 'Home', 'Computing', 'Accessories')),
    vendor           text        NOT NULL DEFAULT '',
    tags             text[]      NOT NULL DEFAULT '{}',
    price_cents      bigint      NOT NULL CHECK (price_cents >= 0),
    compare_at_cents bigint      NOT NULL DEFAULT 0 CHECK (compare_at_cents >= 0),
    cost_cents       bigint      NOT NULL DEFAULT 0 CHECK (cost_cents >= 0),
    stock            integer     NOT NULL DEFAULT 0 CHECK (stock >= 0),
    weight_grams     integer     NOT NULL DEFAULT 0 CHECK (weight_grams >= 0),
    status           text        NOT NULL DEFAULT 'draft' CHECK (status IN ('active', 'draft', 'archived')),
    sold_30d         integer     NOT NULL DEFAULT 0,
    rating           real        NOT NULL DEFAULT 0,
    hue              integer     NOT NULL DEFAULT 0,
    trend            integer[]   NOT NULL DEFAULT '{}',
    description      text        NOT NULL DEFAULT '',
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX products_category_idx ON products (category);
CREATE INDEX products_status_idx ON products (status);

CREATE TABLE product_images (
    id         text        PRIMARY KEY,
    product_id bigint      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    position   integer     NOT NULL,
    url        text        NOT NULL,
    alt        text        NOT NULL DEFAULT '',
    generated  boolean     NOT NULL DEFAULT false,
    size_bytes bigint      NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX product_images_product_idx ON product_images (product_id, position);

CREATE TABLE customers (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text        NOT NULL,
    email             text        NOT NULL,
    phone             text        NOT NULL DEFAULT '',
    country           text        NOT NULL DEFAULT '',
    address_line1     text        NOT NULL DEFAULT '',
    city              text        NOT NULL DEFAULT '',
    postal_code       text        NOT NULL DEFAULT '',
    tags              text[]      NOT NULL DEFAULT '{}',
    accepts_marketing boolean     NOT NULL DEFAULT false,
    source            text        NOT NULL DEFAULT '',
    last_seen_at      timestamptz NOT NULL DEFAULT now(),
    created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX customers_email_key ON customers (lower(email));

CREATE TABLE customer_notes (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint      NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
    author      text        NOT NULL,
    body        text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX customer_notes_customer_idx ON customer_notes (customer_id, created_at DESC);

CREATE TABLE orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint      NOT NULL REFERENCES customers (id),
    status      text        NOT NULL CHECK (status IN ('pending', 'paid', 'shipped', 'delivered', 'refunded', 'failed')),
    payment     text        NOT NULL DEFAULT '',
    total_cents bigint      NOT NULL CHECK (total_cents >= 0),
    placed_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX orders_placed_idx ON orders (placed_at DESC);
CREATE INDEX orders_customer_idx ON orders (customer_id, placed_at DESC);
CREATE INDEX orders_status_idx ON orders (status);

-- Line items are a snapshot of the product at purchase time, so they survive
-- product edits and deletion.
CREATE TABLE order_items (
    order_id    bigint  NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    line        integer NOT NULL,
    product_id  bigint  REFERENCES products (id) ON DELETE SET NULL,
    name        text    NOT NULL,
    sku         text    NOT NULL,
    category    text    NOT NULL,
    hue         integer NOT NULL DEFAULT 0,
    image_url   text    NOT NULL DEFAULT '',
    qty         integer NOT NULL CHECK (qty > 0),
    price_cents bigint  NOT NULL CHECK (price_cents >= 0),
    PRIMARY KEY (order_id, line)
);

-- Dashboard rollups. In a real system a job would refresh these from orders
-- and storefront analytics; here they are seeded.
CREATE TABLE revenue_daily (
    day            date   PRIMARY KEY,
    current_cents  bigint NOT NULL,
    previous_cents bigint NOT NULL
);

CREATE TABLE orders_heatmap (
    dow    smallint NOT NULL CHECK (dow BETWEEN 0 AND 6), -- 0 = Monday
    hour   smallint NOT NULL CHECK (hour BETWEEN 0 AND 23),
    orders integer  NOT NULL,
    PRIMARY KEY (dow, hour)
);

CREATE TABLE activity (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind    text        NOT NULL,
    actor   text        NOT NULL,
    message text        NOT NULL,
    at      timestamptz NOT NULL DEFAULT now()
);

-- Derived customer metrics. Mirrors domain.CustomerSegment: keep them in sync.
CREATE VIEW customers_v AS
SELECT c.*,
       coalesce(s.orders, 0)::int        AS orders,
       coalesce(s.ltv_cents, 0)::bigint  AS ltv_cents,
       s.last_order_at::timestamptz      AS last_order_at,
       CASE
           WHEN s.last_order_at IS NOT NULL AND now() - s.last_order_at > interval '45 days' THEN 'At risk'
           WHEN coalesce(s.ltv_cents, 0) >= 150000 OR coalesce(s.orders, 0) >= 8 THEN 'VIP'
           WHEN coalesce(s.orders, 0) <= 1 OR now() - c.created_at < interval '30 days' THEN 'New'
           ELSE 'Regular'
       END::text AS segment
FROM customers c
LEFT JOIN LATERAL (
    SELECT count(*) FILTER (WHERE o.status NOT IN ('refunded', 'failed'))                     AS orders,
           sum(o.total_cents) FILTER (WHERE o.status NOT IN ('refunded', 'failed'))           AS ltv_cents,
           max(o.placed_at)                                                                 AS last_order_at
    FROM orders o
    WHERE o.customer_id = c.id
) s ON true;

-- +goose Down
DROP VIEW customers_v;
DROP TABLE activity, orders_heatmap, revenue_daily, order_items, orders, customer_notes,
    customers, product_images, products, sessions, members;
