// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: activity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addActivity = `-- name: AddActivity :one
INSERT INTO activity (kind, actor, actor_id, message, entity, entity_id)
VALUES ($1, $2, $6, $3, $4, $5)
RETURNING id, kind, actor, message, at, actor_id, entity, entity_id
`

type AddActivityParams struct {
	Kind     string
	Actor    string
	Message  string
	Entity   string
	EntityID int64
	ActorID  pgtype.Int8
}

func (q *Queries) AddActivity(ctx context.Context, arg AddActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, addActivity,
		arg.Kind,
		arg.Actor,
		arg.Message,
		arg.Entity,
		arg.EntityID,
		arg.ActorID,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Actor,
		&i.Message,
		&i.At,
		&i.ActorID,
		&i.Entity,
		&i.EntityID,
	)
	return i, err
}

const countActivity = `-- name: CountActivity :one
SELECT count(*)::int FROM activity
WHERE ($1::bigint = 0 OR actor_id = $1::bigint)
  AND ($2::text = '' OR kind = $2::text)
  AND (NOT $3::bool OR kind NOT IN ('auth', 'alert'))
  AND ($4::text = '' OR (actor || ' ' || message) ILIKE '%' || $4::text || '%')
`

type CountActivityParams struct {
	ActorID     int64
	Kind        string
	ExcludeAuth bool
	Q           string
}

func (q *Queries) CountActivity(ctx context.Context, arg CountActivityParams) (int32, error) {
	row := q.db.QueryRow(ctx, countActivity,
		arg.ActorID,
		arg.Kind,
		arg.ExcludeAuth,
		arg.Q,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listActivity = `-- name: ListActivity :many
SELECT id, kind, actor, message, at, actor_id, entity, entity_id FROM activity
WHERE ($1::bigint = 0 OR actor_id = $1::bigint)
  AND ($2::text = '' OR kind = $2::text)
  AND (NOT $3::bool OR kind NOT IN ('auth', 'alert'))
  AND ($4::text = '' OR (actor || ' ' || message) ILIKE '%' || $4::text || '%')
ORDER BY at DESC, id DESC
LIMIT $6::int OFFSET $5::int
`

type ListActivityParams struct {
	ActorID     int64
	Kind        string
	ExcludeAuth bool
	Q           string
	Off         int32
	Lim         int32
}

func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivity,
		arg.ActorID,
		arg.Kind,
		arg.ExcludeAuth,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Actor,
			&i.Message,
			&i.At,
			&i.ActorID,
			&i.Entity,
			&i.EntityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
