// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: apikeys.sql

package db

import (
	"context"
)

const aPIKeyByHash = `-- name: APIKeyByHash :one
SELECT id, name, scope, last4, token_hash, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) APIKeyByHash(ctx context.Context, tokenHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, aPIKeyByHash, tokenHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.Last4,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const countAPIKeys = `-- name: CountAPIKeys :one
SELECT count(*)::int FROM api_keys
`

func (q *Queries) CountAPIKeys(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countAPIKeys)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, scope, last4, token_hash, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, scope, last4, token_hash, created_by, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	Name      string
	Scope     string
	Last4     string
	TokenHash []byte
	CreatedBy string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.Scope,
		arg.Last4,
		arg.TokenHash,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.Last4,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, scope, last4, token_hash, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE revoked_at IS NULL ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.Last4,
			&i.TokenHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL RETURNING id, name, scope, last4, token_hash, created_by, created_at, last_used_at, revoked_at
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id int64) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.Last4,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
