// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customers.sql

package db

import (
	"context"
)

const addCustomerNote = `-- name: AddCustomerNote :one
INSERT INTO customer_notes (customer_id, author, body) VALUES ($1, $2, $3) RETURNING id, customer_id, author, body, created_at
`

type AddCustomerNoteParams struct {
	CustomerID int64
	Author     string
	Body       string
}

func (q *Queries) AddCustomerNote(ctx context.Context, arg AddCustomerNoteParams) (CustomerNote, error) {
	row := q.db.QueryRow(ctx, addCustomerNote, arg.CustomerID, arg.Author, arg.Body)
	var i CustomerNote
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const customerSegments = `-- name: CustomerSegments :many
SELECT segment, count(*)::int AS n, coalesce(sum(ltv_cents), 0)::bigint AS ltv_cents
FROM customers_v GROUP BY segment
`

type CustomerSegmentsRow struct {
	Segment  string
	N        int32
	LtvCents int64
}

func (q *Queries) CustomerSegments(ctx context.Context) ([]CustomerSegmentsRow, error) {
	rows, err := q.db.Query(ctx, customerSegments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerSegmentsRow{}
	for rows.Next() {
		var i CustomerSegmentsRow
		if err := rows.Scan(&i.Segment, &i.N, &i.LtvCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, email, phone, country, address_line1, city, postal_code, tags, accepts_marketing, source, last_seen_at, created_at, orders, ltv_cents, last_order_at, segment FROM customers_v WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (CustomersV, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i CustomersV
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.AddressLine1,
		&i.City,
		&i.PostalCode,
		&i.Tags,
		&i.AcceptsMarketing,
		&i.Source,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.Orders,
		&i.LtvCents,
		&i.LastOrderAt,
		&i.Segment,
	)
	return i, err
}

const listCustomerNotes = `-- name: ListCustomerNotes :many
SELECT id, customer_id, author, body, created_at FROM customer_notes WHERE customer_id = ANY($1::bigint[]) ORDER BY created_at DESC
`

func (q *Queries) ListCustomerNotes(ctx context.Context, customerIds []int64) ([]CustomerNote, error) {
	rows, err := q.db.Query(ctx, listCustomerNotes, customerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerNote{}
	for rows.Next() {
		var i CustomerNote
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, email, phone, country, address_line1, city, postal_code, tags, accepts_marketing, source, last_seen_at, created_at, orders, ltv_cents, last_order_at, segment FROM customers_v
WHERE ($1::text = '' OR segment = $1::text)
  AND ($2::text = '' OR (name || ' ' || email || ' ' || city) ILIKE '%' || $2::text || '%')
ORDER BY ltv_cents DESC, id
`

type ListCustomersParams struct {
	Segment string
	Q       string
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]CustomersV, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Segment, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomersV{}
	for rows.Next() {
		var i CustomersV
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.AddressLine1,
			&i.City,
			&i.PostalCode,
			&i.Tags,
			&i.AcceptsMarketing,
			&i.Source,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.Orders,
			&i.LtvCents,
			&i.LastOrderAt,
			&i.Segment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
