// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package db

import (
	"context"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*)::int FROM members
`

func (q *Queries) CountMembers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countMembers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const ordersHeatmap = `-- name: OrdersHeatmap :many
SELECT dow, hour, orders FROM orders_heatmap
`

func (q *Queries) OrdersHeatmap(ctx context.Context) ([]OrdersHeatmap, error) {
	rows, err := q.db.Query(ctx, ordersHeatmap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersHeatmap{}
	for rows.Next() {
		var i OrdersHeatmap
		if err := rows.Scan(&i.Dow, &i.Hour, &i.Orders); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueSeries = `-- name: RevenueSeries :many
SELECT day, current_cents, previous_cents FROM (
    SELECT day, current_cents, previous_cents FROM revenue_daily ORDER BY day DESC LIMIT $1::int
) r ORDER BY day
`

func (q *Queries) RevenueSeries(ctx context.Context, days int32) ([]RevenueDaily, error) {
	rows, err := q.db.Query(ctx, revenueSeries, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueDaily{}
	for rows.Next() {
		var i RevenueDaily
		if err := rows.Scan(&i.Day, &i.CurrentCents, &i.PreviousCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
