// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package db

import (
	"context"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*)::int FROM members
`

func (q *Queries) CountMembers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countMembers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getTarget = `-- name: GetTarget :one
SELECT quarter, goal_cents, updated_by, updated_at FROM targets WHERE quarter = $1
`

func (q *Queries) GetTarget(ctx context.Context, quarter string) (Target, error) {
	row := q.db.QueryRow(ctx, getTarget, quarter)
	var i Target
	err := row.Scan(
		&i.Quarter,
		&i.GoalCents,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTarget = `-- name: UpsertTarget :one
INSERT INTO targets (quarter, goal_cents, updated_by) VALUES ($1, $2, $3)
ON CONFLICT (quarter) DO UPDATE SET goal_cents = EXCLUDED.goal_cents, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING quarter, goal_cents, updated_by, updated_at
`

type UpsertTargetParams struct {
	Quarter   string
	GoalCents int64
	UpdatedBy string
}

func (q *Queries) UpsertTarget(ctx context.Context, arg UpsertTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, upsertTarget, arg.Quarter, arg.GoalCents, arg.UpdatedBy)
	var i Target
	err := row.Scan(
		&i.Quarter,
		&i.GoalCents,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
