// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID       int64
	Kind     string
	Actor    string
	Message  string
	At       time.Time
	ActorID  pgtype.Int8
	Entity   string
	EntityID int64
}

type ApiKey struct {
	ID         int64
	Name       string
	Scope      string
	Last4      string
	TokenHash  []byte
	CreatedBy  string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type Customer struct {
	ID               int64
	Name             string
	Email            string
	Phone            string
	Country          string
	AddressLine1     string
	City             string
	PostalCode       string
	Tags             []string
	AcceptsMarketing bool
	Source           string
	LastSeenAt       time.Time
	CreatedAt        time.Time
}

type CustomerNote struct {
	ID         int64
	CustomerID int64
	Author     string
	Body       string
	CreatedAt  time.Time
}

type CustomersV struct {
	ID               int64
	Name             string
	Email            string
	Phone            string
	Country          string
	AddressLine1     string
	City             string
	PostalCode       string
	Tags             []string
	AcceptsMarketing bool
	Source           string
	LastSeenAt       time.Time
	CreatedAt        time.Time
	Orders           int32
	LtvCents         int64
	LastOrderAt      *time.Time
	Segment          string
}

type Member struct {
	ID                  int64
	Name                string
	Email               string
	Role                string
	Status              string
	Mfa                 bool
	PasswordHash        string
	LastActiveAt        *time.Time
	CreatedAt           time.Time
	Granted             []string
	Revoked             []string
	NotificationsReadAt *time.Time
	InviteHash          []byte
	InviteExpiresAt     *time.Time
}

type Order struct {
	ID           int64
	CustomerID   int64
	Status       string
	Payment      string
	TotalCents   int64
	PlacedAt     time.Time
	RefundReason string
	RefundedBy   string
	RefundedAt   *time.Time
}

type OrderItem struct {
	OrderID    int64
	Line       int32
	ProductID  pgtype.Int8
	Name       string
	Sku        string
	Category   string
	Hue        int32
	ImageUrl   string
	Qty        int32
	PriceCents int64
}

type OrdersHeatmap struct {
	Dow    int16
	Hour   int16
	Orders int32
}

type Product struct {
	ID             int64
	Name           string
	Sku            string
	Category       string
	Vendor         string
	Tags           []string
	PriceCents     int64
	CompareAtCents int64
	CostCents      int64
	Stock          int32
	WeightGrams    int32
	Status         string
	Sold30d        int32
	Rating         float32
	Hue            int32
	Trend          []int32
	Description    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ProductImage struct {
	ID        string
	ProductID int64
	Position  int32
	Url       string
	Alt       string
	Generated bool
	SizeBytes int64
	CreatedAt time.Time
}

type RevenueDaily struct {
	Day           time.Time
	CurrentCents  int64
	PreviousCents int64
}

type Session struct {
	TokenHash []byte
	MemberID  int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Setting struct {
	ID        bool
	Data      []byte
	UpdatedAt time.Time
}

type Target struct {
	Quarter   string
	GoalCents int64
	UpdatedBy string
	UpdatedAt time.Time
}
