// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package db

import (
	"context"
	"time"
)

const countOrders = `-- name: CountOrders :one
SELECT count(*)::int
FROM orders o
JOIN customers c ON c.id = o.customer_id
WHERE ($1::text = '' OR o.status = $1::text)
  AND ($2::bigint = 0 OR o.customer_id = $2::bigint)
  AND ($3::text = ''
       OR (c.name || ' ' || c.email) ILIKE '%' || $3::text || '%'
       OR ('#' || o.id::text) ILIKE '%' || $3::text || '%')
`

type CountOrdersParams struct {
	Status     string
	CustomerID int64
	Q          string
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countOrders, arg.Status, arg.CustomerID, arg.Q)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrder = `-- name: GetOrder :one
SELECT o.id, o.status, o.payment, o.total_cents, o.placed_at,
       c.id AS customer_id, c.name AS customer_name, c.email AS customer_email,
       c.country AS customer_country, c.segment AS customer_segment
FROM orders o
JOIN customers_v c ON c.id = o.customer_id
WHERE o.id = $1
`

type GetOrderRow struct {
	ID              int64
	Status          string
	Payment         string
	TotalCents      int64
	PlacedAt        time.Time
	CustomerID      int64
	CustomerName    string
	CustomerEmail   string
	CustomerCountry string
	CustomerSegment string
}

func (q *Queries) GetOrder(ctx context.Context, id int64) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Payment,
		&i.TotalCents,
		&i.PlacedAt,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerCountry,
		&i.CustomerSegment,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT order_id, line, product_id, name, sku, category, hue, image_url, qty, price_cents FROM order_items WHERE order_id = ANY($1::bigint[]) ORDER BY order_id, line
`

func (q *Queries) ListOrderItems(ctx context.Context, orderIds []int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.Line,
			&i.ProductID,
			&i.Name,
			&i.Sku,
			&i.Category,
			&i.Hue,
			&i.ImageUrl,
			&i.Qty,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT o.id, o.status, o.payment, o.total_cents, o.placed_at,
       c.id AS customer_id, c.name AS customer_name, c.email AS customer_email,
       c.country AS customer_country, c.segment AS customer_segment
FROM orders o
JOIN customers_v c ON c.id = o.customer_id
WHERE ($1::text = '' OR o.status = $1::text)
  AND ($2::bigint = 0 OR o.customer_id = $2::bigint)
  AND ($3::text = ''
       OR (c.name || ' ' || c.email) ILIKE '%' || $3::text || '%'
       OR ('#' || o.id::text) ILIKE '%' || $3::text || '%')
ORDER BY o.placed_at DESC, o.id DESC
LIMIT $5::int OFFSET $4::int
`

type ListOrdersParams struct {
	Status     string
	CustomerID int64
	Q          string
	Off        int32
	Lim        int32
}

type ListOrdersRow struct {
	ID              int64
	Status          string
	Payment         string
	TotalCents      int64
	PlacedAt        time.Time
	CustomerID      int64
	CustomerName    string
	CustomerEmail   string
	CustomerCountry string
	CustomerSegment string
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.Status,
		arg.CustomerID,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Payment,
			&i.TotalCents,
			&i.PlacedAt,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerCountry,
			&i.CustomerSegment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderCounts = `-- name: OrderCounts :many
SELECT status, count(*)::int AS n FROM orders GROUP BY status
`

type OrderCountsRow struct {
	Status string
	N      int32
}

func (q *Queries) OrderCounts(ctx context.Context) ([]OrderCountsRow, error) {
	rows, err := q.db.Query(ctx, orderCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderCountsRow{}
	for rows.Next() {
		var i OrderCountsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE orders SET status = $2 WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
