// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package db

import (
	"context"
)

const addProductImage = `-- name: AddProductImage :exec
INSERT INTO product_images (id, product_id, position, url, alt, generated, size_bytes)
VALUES ($1, $2,
        (SELECT coalesce(max(pi.position) + 1, 0) FROM product_images pi WHERE pi.product_id = $2),
        $3, $4, $5, $6)
`

type AddProductImageParams struct {
	ID        string
	ProductID int64
	Url       string
	Alt       string
	Generated bool
	SizeBytes int64
}

func (q *Queries) AddProductImage(ctx context.Context, arg AddProductImageParams) error {
	_, err := q.db.Exec(ctx, addProductImage,
		arg.ID,
		arg.ProductID,
		arg.Url,
		arg.Alt,
		arg.Generated,
		arg.SizeBytes,
	)
	return err
}

const countProductImages = `-- name: CountProductImages :one
SELECT count(*)::int FROM product_images WHERE product_id = $1
`

func (q *Queries) CountProductImages(ctx context.Context, productID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countProductImages, productID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, sku, category, vendor, tags, price_cents, compare_at_cents, cost_cents,
                      stock, weight_grams, status, description, hue, trend)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, '{0,0,0,0,0,0,0,0,0,0,0,0,0,0}')
RETURNING id, name, sku, category, vendor, tags, price_cents, compare_at_cents, cost_cents, stock, weight_grams, status, sold_30d, rating, hue, trend, description, created_at, updated_at
`

type CreateProductParams struct {
	Name           string
	Sku            string
	Category       string
	Vendor         string
	Tags           []string
	PriceCents     int64
	CompareAtCents int64
	CostCents      int64
	Stock          int32
	WeightGrams    int32
	Status         string
	Description    string
	Hue            int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Sku,
		arg.Category,
		arg.Vendor,
		arg.Tags,
		arg.PriceCents,
		arg.CompareAtCents,
		arg.CostCents,
		arg.Stock,
		arg.WeightGrams,
		arg.Status,
		arg.Description,
		arg.Hue,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.Vendor,
		&i.Tags,
		&i.PriceCents,
		&i.CompareAtCents,
		&i.CostCents,
		&i.Stock,
		&i.WeightGrams,
		&i.Status,
		&i.Sold30d,
		&i.Rating,
		&i.Hue,
		&i.Trend,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProductImage = `-- name: DeleteProductImage :one
DELETE FROM product_images WHERE product_id = $1 AND id = $2 RETURNING id, product_id, position, url, alt, generated, size_bytes, created_at
`

type DeleteProductImageParams struct {
	ProductID int64
	ID        string
}

func (q *Queries) DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, deleteProductImage, arg.ProductID, arg.ID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Position,
		&i.Url,
		&i.Alt,
		&i.Generated,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProducts = `-- name: DeleteProducts :execrows
DELETE FROM products WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteProducts(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProducts, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, sku, category, vendor, tags, price_cents, compare_at_cents, cost_cents, stock, weight_grams, status, sold_30d, rating, hue, trend, description, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.Vendor,
		&i.Tags,
		&i.PriceCents,
		&i.CompareAtCents,
		&i.CostCents,
		&i.Stock,
		&i.WeightGrams,
		&i.Status,
		&i.Sold30d,
		&i.Rating,
		&i.Hue,
		&i.Trend,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, position, url, alt, generated, size_bytes, created_at FROM product_images WHERE product_id = ANY($1::bigint[]) ORDER BY product_id, position, created_at
`

func (q *Queries) ListProductImages(ctx context.Context, productIds []int64) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Position,
			&i.Url,
			&i.Alt,
			&i.Generated,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, sku, category, vendor, tags, price_cents, compare_at_cents, cost_cents, stock, weight_grams, status, sold_30d, rating, hue, trend, description, created_at, updated_at FROM products
WHERE ($1::text = '' OR category = $1::text)
  AND ($2::text = '' OR status = $2::text)
  AND ($3::text = ''
       OR (name || ' ' || sku || ' ' || vendor || ' ' || array_to_string(tags, ' ')) ILIKE '%' || $3::text || '%')
ORDER BY
  CASE WHEN $4::text = 'sales' THEN sold_30d END DESC,
  CASE WHEN $4::text = 'price' THEN price_cents END DESC,
  CASE WHEN $4::text = 'stock' THEN stock END ASC,
  CASE WHEN $4::text = 'name' THEN name END ASC,
  sold_30d::bigint * price_cents DESC,
  id
`

type ListProductsParams struct {
	Category string
	Status   string
	Q        string
	Sort     string
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Category,
		arg.Status,
		arg.Q,
		arg.Sort,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Category,
			&i.Vendor,
			&i.Tags,
			&i.PriceCents,
			&i.CompareAtCents,
			&i.CostCents,
			&i.Stock,
			&i.WeightGrams,
			&i.Status,
			&i.Sold30d,
			&i.Rating,
			&i.Hue,
			&i.Trend,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productCountsByCategory = `-- name: ProductCountsByCategory :many
SELECT category, count(*)::int AS n FROM products GROUP BY category
`

type ProductCountsByCategoryRow struct {
	Category string
	N        int32
}

func (q *Queries) ProductCountsByCategory(ctx context.Context) ([]ProductCountsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, productCountsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductCountsByCategoryRow{}
	for rows.Next() {
		var i ProductCountsByCategoryRow
		if err := rows.Scan(&i.Category, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productImageFiles = `-- name: ProductImageFiles :many
SELECT url FROM product_images WHERE product_id = ANY($1::bigint[]) AND NOT generated
`

func (q *Queries) ProductImageFiles(ctx context.Context, productIds []int64) ([]string, error) {
	rows, err := q.db.Query(ctx, productImageFiles, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productSalesByCategory = `-- name: ProductSalesByCategory :many
SELECT category, coalesce(sum(sold_30d::bigint * price_cents), 0)::bigint AS sales_cents
FROM products GROUP BY category
`

type ProductSalesByCategoryRow struct {
	Category   string
	SalesCents int64
}

func (q *Queries) ProductSalesByCategory(ctx context.Context) ([]ProductSalesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, productSalesByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductSalesByCategoryRow{}
	for rows.Next() {
		var i ProductSalesByCategoryRow
		if err := rows.Scan(&i.Category, &i.SalesCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productStats = `-- name: ProductStats :one
SELECT count(*)::int                                            AS total,
       count(*) FILTER (WHERE status = 'active')::int           AS active,
       count(*) FILTER (WHERE stock > 0 AND stock < 15)::int    AS low_stock,
       count(*) FILTER (WHERE stock = 0)::int                   AS out_of_stock,
       coalesce(sum(stock::bigint * price_cents), 0)::bigint    AS inventory_value_cents
FROM products
`

type ProductStatsRow struct {
	Total               int32
	Active              int32
	LowStock            int32
	OutOfStock          int32
	InventoryValueCents int64
}

func (q *Queries) ProductStats(ctx context.Context) (ProductStatsRow, error) {
	row := q.db.QueryRow(ctx, productStats)
	var i ProductStatsRow
	err := row.Scan(
		&i.Total,
		&i.Active,
		&i.LowStock,
		&i.OutOfStock,
		&i.InventoryValueCents,
	)
	return i, err
}

const setPrimaryImage = `-- name: SetPrimaryImage :execrows
UPDATE product_images AS t
SET position = m.min_position - 1
FROM (SELECT min(position) AS min_position FROM product_images WHERE product_id = $1) AS m
WHERE t.product_id = $1 AND t.id = $2
`

type SetPrimaryImageParams struct {
	ProductID int64
	ImageID   string
}

// Moves the image in front of the current first one.
func (q *Queries) SetPrimaryImage(ctx context.Context, arg SetPrimaryImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPrimaryImage, arg.ProductID, arg.ImageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProductsStatus = `-- name: SetProductsStatus :execrows
UPDATE products SET status = $1, updated_at = now() WHERE id = ANY($2::bigint[])
`

type SetProductsStatusParams struct {
	Status string
	Ids    []int64
}

func (q *Queries) SetProductsStatus(ctx context.Context, arg SetProductsStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProductsStatus, arg.Status, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const topProducts = `-- name: TopProducts :many
SELECT id, name, sku, category, vendor, tags, price_cents, compare_at_cents, cost_cents, stock, weight_grams, status, sold_30d, rating, hue, trend, description, created_at, updated_at FROM products ORDER BY sold_30d::bigint * price_cents DESC, id LIMIT $1::int
`

func (q *Queries) TopProducts(ctx context.Context, lim int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, topProducts, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Category,
			&i.Vendor,
			&i.Tags,
			&i.PriceCents,
			&i.CompareAtCents,
			&i.CostCents,
			&i.Stock,
			&i.WeightGrams,
			&i.Status,
			&i.Sold30d,
			&i.Rating,
			&i.Hue,
			&i.Trend,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchProduct = `-- name: TouchProduct :exec
UPDATE products SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name             = $1,
    sku              = $2,
    -- Right-hand side sees the old row, so the hue only changes with the category.
    hue              = CASE WHEN category <> $3::text THEN $4::int ELSE hue END,
    category         = $3::text,
    vendor           = $5,
    tags             = $6,
    price_cents      = $7,
    compare_at_cents = $8,
    cost_cents       = $9,
    stock            = $10,
    weight_grams     = $11,
    status           = $12,
    description      = $13,
    updated_at       = now()
WHERE id = $14
RETURNING id, name, sku, category, vendor, tags, price_cents, compare_at_cents, cost_cents, stock, weight_grams, status, sold_30d, rating, hue, trend, description, created_at, updated_at
`

type UpdateProductParams struct {
	Name           string
	Sku            string
	Category       string
	Hue            int32
	Vendor         string
	Tags           []string
	PriceCents     int64
	CompareAtCents int64
	CostCents      int64
	Stock          int32
	WeightGrams    int32
	Status         string
	Description    string
	ID             int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Sku,
		arg.Category,
		arg.Hue,
		arg.Vendor,
		arg.Tags,
		arg.PriceCents,
		arg.CompareAtCents,
		arg.CostCents,
		arg.Stock,
		arg.WeightGrams,
		arg.Status,
		arg.Description,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.Vendor,
		&i.Tags,
		&i.PriceCents,
		&i.CompareAtCents,
		&i.CostCents,
		&i.Stock,
		&i.WeightGrams,
		&i.Status,
		&i.Sold30d,
		&i.Rating,
		&i.Hue,
		&i.Trend,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
