// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: team.sql

package db

import (
	"context"
	"time"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (name, email, role) VALUES ($1, $2, $3) RETURNING id, name, email, role, status, mfa, password_hash, last_active_at, created_at, granted, revoked
`

type CreateMemberParams struct {
	Name  string
	Email string
	Role  string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.Name, arg.Email, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.Mfa,
		&i.PasswordHash,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.Granted,
		&i.Revoked,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, member_id, expires_at) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	MemberID  int64
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.MemberID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMemberSessions = `-- name: DeleteMemberSessions :exec
DELETE FROM sessions WHERE member_id = $1
`

func (q *Queries) DeleteMemberSessions(ctx context.Context, memberID int64) error {
	_, err := q.db.Exec(ctx, deleteMemberSessions, memberID)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :execrows
DELETE FROM sessions WHERE token_hash <> $1
`

func (q *Queries) DeleteOtherSessions(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessions, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, name, email, role, status, mfa, password_hash, last_active_at, created_at, granted, revoked FROM members WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id int64) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.Mfa,
		&i.PasswordHash,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.Granted,
		&i.Revoked,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, name, email, role, status, mfa, password_hash, last_active_at, created_at, granted, revoked FROM members WHERE ($1::text = '' OR role = $1::text) ORDER BY id
`

func (q *Queries) ListMembers(ctx context.Context, role string) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.Mfa,
			&i.PasswordHash,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.Granted,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberByEmail = `-- name: MemberByEmail :one
SELECT id, name, email, role, status, mfa, password_hash, last_active_at, created_at, granted, revoked FROM members WHERE lower(email) = lower($1::text)
`

func (q *Queries) MemberByEmail(ctx context.Context, email string) (Member, error) {
	row := q.db.QueryRow(ctx, memberByEmail, email)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.Mfa,
		&i.PasswordHash,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.Granted,
		&i.Revoked,
	)
	return i, err
}

const setMemberAccess = `-- name: SetMemberAccess :one
UPDATE members SET granted = $1::text[], revoked = $2::text[] WHERE id = $3 RETURNING id, name, email, role, status, mfa, password_hash, last_active_at, created_at, granted, revoked
`

type SetMemberAccessParams struct {
	Granted []string
	Revoked []string
	ID      int64
}

func (q *Queries) SetMemberAccess(ctx context.Context, arg SetMemberAccessParams) (Member, error) {
	row := q.db.QueryRow(ctx, setMemberAccess, arg.Granted, arg.Revoked, arg.ID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.Mfa,
		&i.PasswordHash,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.Granted,
		&i.Revoked,
	)
	return i, err
}

const setMemberStatus = `-- name: SetMemberStatus :one
UPDATE members SET status = $2 WHERE id = $1 RETURNING id, name, email, role, status, mfa, password_hash, last_active_at, created_at, granted, revoked
`

type SetMemberStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) SetMemberStatus(ctx context.Context, arg SetMemberStatusParams) (Member, error) {
	row := q.db.QueryRow(ctx, setMemberStatus, arg.ID, arg.Status)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.Mfa,
		&i.PasswordHash,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.Granted,
		&i.Revoked,
	)
	return i, err
}

const touchMember = `-- name: TouchMember :exec
UPDATE members SET last_active_at = now() WHERE id = $1
`

func (q *Queries) TouchMember(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchMember, id)
	return err
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions SET expires_at = $1
WHERE token_hash = $2 AND expires_at > now()
RETURNING member_id
`

type TouchSessionParams struct {
	ExpiresAt time.Time
	TokenHash []byte
}

// Sliding expiry: returns the member only while the session is still valid.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.ExpiresAt, arg.TokenHash)
	var member_id int64
	err := row.Scan(&member_id)
	return member_id, err
}

const updateMember = `-- name: UpdateMember :one
UPDATE members SET name = $2, email = $3, role = $4 WHERE id = $1 RETURNING id, name, email, role, status, mfa, password_hash, last_active_at, created_at, granted, revoked
`

type UpdateMemberParams struct {
	ID    int64
	Name  string
	Email string
	Role  string
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.Mfa,
		&i.PasswordHash,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.Granted,
		&i.Revoked,
	)
	return i, err
}
